FROM scivm/scientific-python-2.7

MAINTAINER Dibyo Majumdar <dibyo.majumdar@gmail.com>


ENV PYTHONPATH /usr/local/raas/src:/usr/local/raas/src/raas_example

RUN apt-get install -y apt-utils
RUN apt-get install -y python-numpy python-scipy python-setuptools
RUN easy_install pytz

